const emailData = [
    {
        "mid": "209834578",
        "year": "2013",
        "month": "3",
        "day": "12",
        "hour": "3",
        "minute": "3",
        "day_of_year": "125",
        "day_of_week": "2",
        "day_since_hire": "2345",
        "sender": "emily",
        "rcpt": "lucy",
        "rcpt Count": "1",
        "size": "9087",
        "files": "sunlife internal",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active "
    },
    {
        "mid": "209834579",
        "year": "2014",
        "month": "4",
        "day": "13",
        "hour": "3",
        "minute": "3",
        "day_of_year": "125",
        "day_of_week": "2",
        "day_since_hire": "2345",
        "sender": "jamie",
        "rcpt": "elly",
        "rcpt Count": "1",
        "size": "9087",
        "files": "business schedule",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active "
    },
    {
        "mid": "209834580",
        "year": "2015",
        "month": "5",
        "day": "14",
        "hour": "3",
        "minute": "3",
        "day_of_year": "125",
        "day_of_week": "2",
        "day_since_hire": "2345",
        "sender": "lucy",
        "rcpt": "sharon",
        "rcpt Count": "1",
        "size": "9087",
        "files": "random picture",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active "
    },
    {
        "mid": "209834581",
        "year": "2016",
        "month": "5",
        "day": "15",
        "hour": "3",
        "minute": "3",
        "day_of_year": "125",
        "day_of_week": "2",
        "day_since_hire": "2345",
        "sender": "elly",
        "rcpt": "jackson",
        "rcpt Count": "1",
        "size": "9087",
        "files": "important notice",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active "
    },
    {
        "mid": "209834582",
        "year": "2017",
        "month": "5",
        "day": "16",
        "hour": "3",
        "minute": "3",
        "day_of_year": "125",
        "day_of_week": "2",
        "day_since_hire": "2345",
        "sender": "sharon",
        "rcpt": "tuntun",
        "rcpt Count": "1",
        "size": "9087",
        "files": "important notice",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active "
    },
    {
        "mid": "209834583",
        "year": "2018",
        "month": "5",
        "day": "17",
        "hour": "3",
        "minute": "3",
        "day_of_year": "125",
        "day_of_week": "2",
        "day_since_hire": "2345",
        "sender": "jackson",
        "rcpt": "keivan",
        "rcpt Count": "1",
        "size": "9087",
        "files": "business document",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active "
    },
    {
        "mid": "209834584",
        "year": "2019",
        "month": "5",
        "day": "18",
        "hour": "3",
        "minute": "3",
        "day_of_year": "125",
        "day_of_week": "2",
        "day_since_hire": "2345",
        "sender": "tuntun",
        "rcpt": "kyle",
        "rcpt Count": "1",
        "size": "9087",
        "files": "important notice",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active "
    },
    {
        "mid": "209834585",
        "year": "2020",
        "month": "5",
        "day": "19",
        "hour": "3",
        "minute": "3",
        "day_of_year": "125",
        "day_of_week": "2",
        "day_since_hire": "2345",
        "sender": "keivan",
        "rcpt": "emily",
        "rcpt Count": "1",
        "size": "9087",
        "files": "quick notice",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active "
    },
    {
        "mid": "209834586",
        "year": "2021",
        "month": "5",
        "day": "20",
        "hour": "3",
        "minute": "3",
        "day_of_year": "125",
        "day_of_week": "2",
        "day_since_hire": "2345",
        "sender": "kyle",
        "rcpt": "jamie",
        "rcpt Count": "1",
        "size": "9087",
        "files": "random files",
        "files_sensitive_count": "1",
        "subject": "urgent",
        "lev_mail": "1",
        "file count": "2",
        "division": "sunlife",
        "employee_status ": "active "
    }
]

export default emailData